# LLM_CONTEXT_MARKER: AI_MULTI_AGENT_01
# MEMORY_VERSION: 1.0.0
# INTERACTION_TIMESTAMP: 2024-11-19

# CRITICAL_PATHS {
PATH_SRC_LIB="src/lib"
PATH_SRC_AGENTS="src/agents"
PATH_ENV=".env"
PATH_DOCS="docs"
# }

# CORE_COMPONENTS {
COMPONENT_API_CLIENT="${PATH_SRC_LIB}/apiClient.js"
COMPONENT_BASE_AGENT="${PATH_SRC_AGENTS}/BaseAgent.js"
COMPONENT_SPECIALIZED_AGENTS="${PATH_SRC_AGENTS}/SpecializedAgents.js"
# }

# INTERACTION_PATTERNS {
PATTERN_URL_HANDLING="FULL_URL_PREFERRED"
PATTERN_ENV_VARS="MINIMAL_EXPLICIT"
PATTERN_CODE_ORGANIZATION="MODULAR_AGENT_BASED"
# }

# CRITICAL_LEARNINGS {
L1="API_URL_CONSTRUCTION:PREFER_FULL_URL:AVOID_COMPONENT_BASED"
L2="ENV_VARS:KEEP_ALL_VARS:NO_COMMENTING_OUT"
L3="AGENT_CONFIG:ALIGN_WITH_API_CLIENT:MAINTAIN_CONSISTENCY"
# }

# FILE_PURPOSES {
F1="${COMPONENT_API_CLIENT}:API_INTERFACE:HANDLES_CUSTOM_OPENAI_ENDPOINTS"
F2="${COMPONENT_BASE_AGENT}:AGENT_FOUNDATION:MANAGES_API_CLIENT_CONFIG"
F3="${COMPONENT_SPECIALIZED_AGENTS}:AGENT_IMPLEMENTATIONS:DEFINES_SPECIFIC_BEHAVIORS"
# }

# REFERENCE_CHAIN {
RC1="ENV_VARS->BASE_AGENT->API_CLIENT"
RC2="SPECIALIZED_AGENTS->BASE_AGENT->API_CLIENT"
# }

# SUCCESS_PATTERNS {
SP1="URL_HANDLING:SINGLE_SOURCE:NO_CONSTRUCTION"
SP2="CONFIG_FLOW:ENV->AGENT->CLIENT:DIRECT_PATH"
SP3="ERROR_HANDLING:EXPLICIT:INFORMATIVE"
# }

# OPTIMIZATION_TARGETS {
OT1="MINIMIZE_ENV_VARS:USE_FULL_URLS"
OT2="MAINTAIN_BACKWARD_COMPATIBILITY"
OT3="CLEAR_ERROR_PROPAGATION"
# }

# MEMORY_ANCHORS {
MA1="URL_TRANSITION:COMPONENT->FULL"
MA2="ENV_VAR_PRESERVATION"
MA3="CONFIG_ALIGNMENT"
# }
